#ToDo
#take input from the user (using 'paper, rock, scissors').
#generate a randomly choice by computer.
#if computer random choice == user's choice print "It's a tie".
#elif PlayerChoice == 'p' and Pc_Choice == 'r' or PlayerChoice == 'r' and Pc_Choice == 's' or PlayerChoice == 's' and Pc_Choice == 'p' print that the user wins.
#else print that computer represented as 'I' wins.







###########These comments was generated by Chatgpt. I will check it later###############

# Rock, Paper, Scissors Game

# Import the random module for generating computer choices

# 1. Introduction
# Display a welcome message to the player
# Explain the rules of the game

# 2. Game Loop
# Use a while True loop to allow the game to continue until the player decides to stop

    # 3. Player Input
    # Prompt the player to make a choice ('p' for paper, 'r' for rock, or 's' for scissors)
    # Convert the input to lowercase for consistency

    # 4. Computer Choice
    # Randomly generate the computer's choice ('p', 'r', or 's')

    # 5. Validate Player Input
    # Check if the player's choice is valid
    # If not, display an error message and continue to the next iteration of the loop

    # 6. Display Choices
    # Display the player's and computer's choices

    # 7. Determine Winner
    # Check the conditions to determine the winner and display the result

    # 8. Display Result
    # Display the result of the game

    # 9. Ask if the Player Wants to Continue
    # If the player wants to continue, the loop continues
    # If not, the loop breaks, and the game ends